src/urls.py
from debug_toolbar.toolbar import debug_toolbar_urls
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("wor.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
] + debug_toolbar_urls()

wor/urls.py
from django.urls import path

from . import views

app_name = "wor"
urlpatterns = [
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path("", views.index_show_view, name="index"),
    path("compareEquipmentForm/", views.compare_equipment_form_view, name="compare_equipment_url"),
    path("characterShow/", views.CharacterView.as_view(), name="show_character_url"),
    path("characterForm/", views.character_form_view, name="character_url"),
    path("weaponForm/", views.weapon_form_view, name="weapon_url"),
    path("chestplateForm/", views.chestplate_form_view, name="chestplate_url"),
    path("wristbandForm/", views.wristband_form_view, name="wristband_url"),
    path("amuletForm/", views.amulet_form_view, name="amulet_url"),
    path("ringForm/", views.ring_form_view, name="ring_url"),
    path("pantheonForm/", views.pantheon_form_view, name="pantheon_url"),
    path("artifactForm/", views.artifact_form_view, name="artifact_url"),
    path("collectionForm/", views.collection_form_view, name="collection_url"),
    path("weaponShow/", views.weapon_show_view, name="show_weapon_url"),
    path("chestplateShow/", views.chestplate_show_view, name="show_chestplate_url"),
    path("wristbandShow/", views.wristband_show_view, name="show_wristband_url"),
    path("amuletShow/", views.amulet_show_view, name="show_amulet_url"),
    path("ringShow/", views.ring_show_view, name="show_ring_url"),
    path("pantheon/", views.pantheon_show_view, name="show_pantheon_url"),
    path("artifact/", views.artifact_show_view, name="show_artifact_url"),
    path("collection/", views.collection_show_view, name="show_collection_url"),
    path("character/<int:f_id>/change", views.character_update_view, name="update_character_url"),
    path("weapon/<int:f_id>/change", views.weapon_update_view, name="update_weapon_url"),
    path("chestplate/<int:f_id>/change", views.chestplate_update_view, name="update_chestplate_url"),
    path("wristband/<int:f_id>/change", views.wristband_update_view, name="update_wristband_url"),
    path("amulet/<int:f_id>/change", views.amulet_update_view, name="update_amulet_url"),
    path("ring/<int:f_id>/change", views.ring_update_view, name="update_ring_url"),
    path("pantheon/<int:f_id>/change", views.pantheon_update_view, name="update_pantheon_url"),
    path("artifact/<int:f_id>/change", views.artifact_update_view, name="update_artifact_url"),
    path("collection/<int:f_id>/change", views.collection_update_view, name="update_collection_url"),
    path("weapon/<int:f_id>/delete", views.weapon_delete_view, name="delete_weapon_url"),
    path("chestplate/<int:f_id>/delete", views.chestplate_delete_view, name="delete_chestplate_url"),
    path("wristband/<int:f_id>/delete", views.wristband_delete_view, name="delete_wristband_url"),
    path("amulet/<int:f_id>/delete", views.amulet_delete_view, name="delete_amulet_url"),
    path("ring/<int:f_id>/delete", views.ring_delete_view, name="delete_ring_url"),
    path("artifact/<int:f_id>/change", views.artifact_delete_view, name="delete_artifact_url"),
    path("weapon/<int:id>", views.weapon_detail, name="weapon-detail"),
    path("chestplate/<int:id>/", views.chestplate_detail, name="chestplate-detail"),
    path("wristband/<int:id>/", views.wristband_detail, name="wristband-detail"),
    path("amulet/<int:id>/", views.amulet_detail, name="amulet-detail"),
    path("ring/<int:id>/", views.ring_detail, name="ring-detail"),
    path("character/<int:id>/", views.character_detail, name="character-detail"),
]

wor/views.py
from django.contrib.auth import get_user
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.views import generic
from django.views.generic import CreateView

from .forms import (
    AmuletForm,
    CharacterForm,
    ChestplateForm,
    CompareEquipmentForm,
    RingForm,
    WeaponForm,
    WristbandForm,
    PantheonForm,
    ArtifactForm,
    CollectionForm,
    WatcherCollectionForm,
    NorthCollectionForm,
    CurseCollectionForm,
    InfernalCollectionForm,
    NightmareCollectionForm,
    ChaosDominionCollectionForm,
    PiercerCollectionForm,
    EsotericCollectionForm,
    ArbitersCollectionForm,
)
from .models import Amulet, Character, Chestplate, Ring, Weapon, Wristband, Pantheon, Artifact, Collection, Faction

resultlist: list[object] = []


class SignUpView(CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy("login")
    template_name = "wor/registration/signup.html"


@login_required
def index_show_view(request):
    template_name = "wor/base.html"
    return render(request, template_name)


def compare_equipment_form_view(request):
    template_name = "wor/form/compare_equipment_form.html"
    user: User = get_user(request)
    if request.method == "POST":
        form = CompareEquipmentForm(request.POST)
        if form.is_valid():
            context = {
                "form": form,
                "character_list": Character.objects.order_by("name"),
                "result_list": form.compare(),
                "characterEquipList": form.characterEquipList,
                "user_id": user.id,
            }
            return render(request, template_name, context)
    if request.method == "GET" and len(CompareEquipmentForm(request.GET).resultlist) > 0:
        form = CompareEquipmentForm(request.GET)
        context = {
            "result": form.resultlist[int(request.GET.get("result_id"))] if request.GET.get("result_id") else None,
            "form": form,
            "character_list": Character.objects.order_by("name"),
            "result_list": form.resultlist,
            "characterEquipList": form.characterEquipList,
            "user_id": user.id,
        }
        CompareEquipmentForm(request.GET).resultlist = []
        return render(request, template_name, context)
    form = CompareEquipmentForm()
    context = {
        "form": form,
        "character_list": Character.objects.order_by("name"),
        "user_id": user.id,
    }
    return render(request, template_name, context)


class CharacterView(generic.ListView):
    template_name = "wor/show/characters.html"
    context_object_name = "character_list"

    def get_queryset(self):
        return Character.objects.order_by("name")


def character_detail(request, id):
    character = Character.objects.get(id=id)
    user: User = get_user(request)
    character.user_id = user.id
    template_name = "wor/detail/character_detail.html"
    context = {"character": character}
    return render(request, template_name, context)


def character_form_view(request):
    form = CharacterForm()
    if request.method == "POST":
        form = CharacterForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("wor:show_character_url")
    template_name = "wor/form/character_form.html"
    context = {"form": form}
    return render(request, template_name, context)


def weapon_form_view(request):
    form = WeaponForm()
    if request.method == "POST":
        form = WeaponForm(request.POST)
        user: User = get_user(request)
        form.user = user
        form.instance.user_id = user.id
        if form.is_valid():
            form.save()
            return redirect("wor:show_weapon_url")
    template_name = "wor/form/weapon_form.html"
    context = {"form": form}
    return render(request, template_name, context)


def chestplate_form_view(request):
    form = ChestplateForm()
    if request.method == "POST":
        form = ChestplateForm(request.POST)
        user: User = get_user(request)
        form.user = user
        form.instance.user_id = user.id
        if form.is_valid():
            form.save()
            return redirect("wor:show_chestplate_url")
    template_name = "wor/form/chestplate_form.html"
    context = {"form": form}
    return render(request, template_name, context)


def wristband_form_view(request):
    form = WristbandForm()
    if request.method == "POST":
        form = WristbandForm(request.POST)
        user: User = get_user(request)
        form.user = user
        form.instance.user_id = user.id
        if form.is_valid():
            form.save()
            return redirect("wor:show_wristband_url")
    template_name = "wor/form/wristband_form.html"
    context = {"form": form}
    return render(request, template_name, context)


def amulet_form_view(request):
    form = AmuletForm()
    if request.method == "POST":
        form = AmuletForm(request.POST)
        user: User = get_user(request)
        form.user = user
        form.instance.user_id = user.id
        if form.is_valid():
            form.save()
            return redirect("wor:show_amulet_url")
    template_name = "wor/form/amulet_form.html"
    context = {"form": form}
    return render(request, template_name, context)


def ring_form_view(request):
    form = RingForm()
    if request.method == "POST":
        form = RingForm(request.POST)
        user: User = get_user(request)
        form.user = user
        form.instance.user_id = user.id
        if form.is_valid():
            form.save()
            return redirect("wor:show_ring_url")
    template_name = "wor/form/ring_form.html"
    context = {"form": form}
    return render(request, template_name, context)


def pantheon_form_view(request):
    form = PantheonForm()
    if request.method == "POST":
        form = PantheonForm(request.POST)
        user: User = get_user(request)
        form.user = user
        form.instance.user_id = user.id
        if form.is_valid():
            form.save()
            return redirect("wor:show_pantheon_url")
    template_name = "wor/form/pantheon_form.html"
    context = {"form": form}
    return render(request, template_name, context)


def artifact_form_view(request):
    form = ArtifactForm()
    if request.method == "POST":
        form = ArtifactForm(request.POST)
        user: User = get_user(request)
        form.user = user
        form.instance.user_id = user.id
        if form.is_valid():
            form.save()
            return redirect("wor:show_artifact_url")
    template_name = "wor/form/artifact_form.html"
    context = {"form": form}
    return render(request, template_name, context)


def collection_form_view(request):
    form = CollectionForm()
    user: User = get_user(request)
    if request.method == "POST":
        updated_request = request.POST.copy()
        faction: Faction = Faction.objects.get(faction=Faction.FactionEnum.WATCHER)
        updated_request.update({'faction': faction})
        form = WatcherCollectionForm(updated_request)
        form.user = user
        form.instance.user_id = user.id
        if form.is_valid():
            form.save()
        faction: Faction = Faction.objects.get(faction=Faction.FactionEnum.NORTH)
        updated_request.update({'faction': faction})
        form = NorthCollectionForm(updated_request)
        form.user = user
        form.instance.user_id = user.id
        if form.is_valid():
            form.save()
        faction: Faction = Faction.objects.get(faction=Faction.FactionEnum.CURSE)
        updated_request.update({'faction': faction})
        form = CurseCollectionForm(updated_request)
        form.user = user
        form.instance.user_id = user.id
        if form.is_valid():
            form.save()
        faction: Faction = Faction.objects.get(faction=Faction.FactionEnum.NIGHTMARE)
        updated_request.update({'faction': faction})
        form = NightmareCollectionForm(updated_request)
        form.user = user
        form.instance.user_id = user.id
        if form.is_valid():
            form.save()
        faction: Faction = Faction.objects.get(faction=Faction.FactionEnum.INFERNAL)
        updated_request.update({'faction': faction})
        form = InfernalCollectionForm(updated_request)
        form.user = user
        form.instance.user_id = user.id
        if form.is_valid():
            form.save()
        faction: Faction = Faction.objects.get(faction=Faction.FactionEnum.PIERCER)
        updated_request.update({'faction': faction})
        form = PiercerCollectionForm(updated_request)
        form.user = user
        form.instance.user_id = user.id
        if form.is_valid():
            form.save()
        faction: Faction = Faction.objects.get(faction=Faction.FactionEnum.ESOTERIC)
        updated_request.update({'faction': faction})
        form = EsotericCollectionForm(updated_request)
        form.user = user
        form.instance.user_id = user.id
        if form.is_valid():
            form.save()
        faction: Faction = Faction.objects.get(faction=Faction.FactionEnum.CHAOS_DOMINION)
        updated_request.update({'faction': faction})
        form = ChaosDominionCollectionForm(updated_request)
        form.user = user
        form.instance.user_id = user.id
        if form.is_valid():
            form.save()
        faction: Faction = Faction.objects.get(faction=Faction.FactionEnum.ARBITERS)
        updated_request.update({'faction': faction})
        form = ArbitersCollectionForm(updated_request)
        form.user = user
        form.instance.user_id = user.id
        if form.is_valid():
            form.save()
        return redirect("wor:show_collection_url")
    template_name = "wor/form/collection_form.html"
    factions = Faction.objects.all()

wor/templates/wor/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset='utf-8'>
        <meta http-equiv='X-UA-Compatible' content='IE=edge'>
        {% block title %}
            <title>Wor</title>
        {% endblock %}
        {% load static %}
        <meta name='viewport' content='width=device-width, initial-scale=1'>
        <link rel="stylesheet" href="{% static 'wor/style.css' %}">
    </head>
    <body>
        <header>
        {% if user.is_authenticated %}
            <form action="{% url 'logout' %}" method="post">
                {% csrf_token %}
                User: {{ user.get_username }}
                <button type="submit">Log Out</button>
            </form>
            <nav>
                <a href="/">Accueil</a>
                <div>
                    <ul>
                        <li>
                            <a href="{% url 'wor:compare_equipment_url' %}">Compare Equipment</a>
                        </li>
                        <li>
                            <a href="{% url 'wor:character_url' %}">Add Character</a>
                        </li>
                        <li>
                            <a href="{% url 'wor:weapon_url' %}">Add Weapon</a>
                        </li>
                        <li>
                            <a href="{% url 'wor:chestplate_url' %}">Add Chestplate</a>
                        </li>
                        <li>
                            <a href="{% url 'wor:wristband_url' %}">Add Wristband</a>
                        </li>
                        <li>
                            <a href="{% url 'wor:amulet_url' %}">Add Amulet</a>
                        </li>
                        <li>
                            <a href="{% url 'wor:ring_url' %}">Add Rings</a>
                        </li>
                        <li>
                            <a href="{% url 'wor:artifact_url' %}">Add Artifacts</a>
                        </li>
                        <li>
                            <a href="{% url 'wor:show_weapon_url' %}">Show Weapons</a>
                        </li>
                        <li>
                            <a href="{% url 'wor:show_chestplate_url' %}">Show Chestplates</a>
                        </li>
                        <li>
                            <a href="{% url 'wor:show_wristband_url' %}">Show Wristbands</a>
                        </li>
                        <li>
                            <a href="{% url 'wor:show_amulet_url' %}">Show Amulets</a>
                        </li>
                        <li>
                            <a href="{% url 'wor:show_ring_url' %}">Show Rings</a>
                        </li>
                        <li>
                            <a href="{% url 'wor:show_character_url' %}">Show Characters</a>
                        </li>
                        <li>
                            <a href="{% url 'wor:show_pantheon_url' %}">Show Pantheon</a>
                        </li>
                        <li>
                            <a href="{% url 'wor:show_collection_url' %}">Show Collection</a>
                        </li>
                        <li>
                            <a href="{% url 'wor:show_artifact_url' %}">Show Artifacts</a>
                        </li>
                    </ul>
                </div>
            </nav>
        {% else %}
            <a href="{% url 'login' %}">login</a> / <a href="{% url 'wor:signup' %}">signup</a>
        {% endif %}
        </header>
        <main>
            {% block content %}
            {% endblock %}
        </main>
    </body>
</html>