src/urls.py
from debug_toolbar.toolbar import debug_toolbar_urls
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("wor.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
] + debug_toolbar_urls()

wor/urls.py
from django.urls import path

from . import views

app_name = "wor"
urlpatterns = [
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path("", views.index_show_view, name="index"),
    path("compareEquipmentForm/", views.compare_equipment_form_view, name="compare_equipment_url"),
    path("characterShow/", views.CharacterView.as_view(), name="show_character_url"),
    path("characterForm/", views.character_form_view, name="character_url"),
    path("weaponForm/", views.weapon_form_view, name="weapon_url"),
    path("chestplateForm/", views.chestplate_form_view, name="chestplate_url"),
    path("wristbandForm/", views.wristband_form_view, name="wristband_url"),
    path("amuletForm/", views.amulet_form_view, name="amulet_url"),
    path("ringForm/", views.ring_form_view, name="ring_url"),
    path("pantheonForm/", views.pantheon_form_view, name="pantheon_url"),
    path("artifactForm/", views.artifact_form_view, name="artifact_url"),
    path("collectionForm/", views.collection_form_view, name="collection_url"),
    path("weaponShow/", views.weapon_show_view, name="show_weapon_url"),
    path("chestplateShow/", views.chestplate_show_view, name="show_chestplate_url"),
    path("wristbandShow/", views.wristband_show_view, name="show_wristband_url"),
    path("amuletShow/", views.amulet_show_view, name="show_amulet_url"),
    path("ringShow/", views.ring_show_view, name="show_ring_url"),
    path("pantheon/", views.pantheon_show_view, name="show_pantheon_url"),
    path("artifact/", views.artifact_show_view, name="show_artifact_url"),
    path("collection/", views.collection_show_view, name="show_collection_url"),
    path("character/<int:f_id>/change", views.character_update_view, name="update_character_url"),
    path("weapon/<int:f_id>/change", views.weapon_update_view, name="update_weapon_url"),
    path("chestplate/<int:f_id>/change", views.chestplate_update_view, name="update_chestplate_url"),
    path("wristband/<int:f_id>/change", views.wristband_update_view, name="update_wristband_url"),
    path("amulet/<int:f_id>/change", views.amulet_update_view, name="update_amulet_url"),
    path("ring/<int:f_id>/change", views.ring_update_view, name="update_ring_url"),
    path("pantheon/<int:f_id>/change", views.pantheon_update_view, name="update_pantheon_url"),
    path("artifact/<int:f_id>/change", views.artifact_update_view, name="update_artifact_url"),
    path("collection/<int:f_id>/change", views.collection_update_view, name="update_collection_url"),
    path("weapon/<int:f_id>/delete", views.weapon_delete_view, name="delete_weapon_url"),
    path("chestplate/<int:f_id>/delete", views.chestplate_delete_view, name="delete_chestplate_url"),
    path("wristband/<int:f_id>/delete", views.wristband_delete_view, name="delete_wristband_url"),
    path("amulet/<int:f_id>/delete", views.amulet_delete_view, name="delete_amulet_url"),
    path("ring/<int:f_id>/delete", views.ring_delete_view, name="delete_ring_url"),
    path("artifact/<int:f_id>/change", views.artifact_delete_view, name="delete_artifact_url"),
    path("weapon/<int:id>", views.weapon_detail, name="weapon-detail"),
    path("chestplate/<int:id>/", views.chestplate_detail, name="chestplate-detail"),
    path("wristband/<int:id>/", views.wristband_detail, name="wristband-detail"),
    path("amulet/<int:id>/", views.amulet_detail, name="amulet-detail"),
    path("ring/<int:id>/", views.ring_detail, name="ring-detail"),
    path("character/<int:id>/", views.character_detail, name="character-detail"),
]

wor/forms.py
import copy

from django import forms

from .models import Amulet, Character, Chestplate, Ring, Weapon, Wristband, Pantheon, Artifact, Collection


def equipment_goodvalue(self, crt_character: Character) -> bool:
    good_hp_value = False
    good_atk_value = False
    good_def_value = False
    good_crit_rate_value = False
    good_crit_dmg_value = False
    good_vit_interval_value = False
    good_rage_regen_value = False
    good_heal_effect_value = False
    if self.cleaned_data['hp_min'] or self.cleaned_data['hp_max']:
        if (
            (self.cleaned_data['hp_min'] if self.cleaned_data['hp_min'] else 0)
            < crt_character.total_hp
            < (self.cleaned_data['hp_max'] if self.cleaned_data['hp_max'] else 999999)
        ):
            good_hp_value = True
    else:
        good_hp_value = True
    if self.cleaned_data['atk_min'] or self.cleaned_data['atk_max']:
        if (
            (self.cleaned_data['atk_min'] if self.cleaned_data['atk_min'] else 0)
            < crt_character.total_atk
            < (self.cleaned_data['atk_max'] if self.cleaned_data['atk_max'] else 999999)
        ):
            good_atk_value = True
    else:
        good_atk_value = True
    if self.cleaned_data['def_min'] or self.cleaned_data['def_max']:
        if (
            (self.cleaned_data['def_min'] if self.cleaned_data['def_min'] else 0)
            < crt_character.total_def
            < (self.cleaned_data['def_max'] if self.cleaned_data['def_max'] else 999999)
        ):
            good_def_value = True
    else:
        good_def_value = True
    if self.cleaned_data['crit_rate_min'] or self.cleaned_data['crit_rate_max']:
        if (
            (self.cleaned_data['crit_rate_min'] if self.cleaned_data['crit_rate_min'] else 0)
            < crt_character.total_crit_rate
            < (self.cleaned_data['crit_rate_max'] if self.cleaned_data['crit_rate_max'] else 999999)
        ):
            good_crit_rate_value = True
    else:
        good_crit_rate_value = True
    if self.cleaned_data['crit_dmg_min'] or self.cleaned_data['crit_dmg_max']:
        if (
            (self.cleaned_data['crit_dmg_min'] if self.cleaned_data['crit_dmg_min'] else 0)
            < crt_character.total_crit_dmg
            < (self.cleaned_data['crit_dmg_max'] if self.cleaned_data['crit_dmg_max'] else 999999)
        ):
            good_crit_dmg_value = True
    else:
        good_crit_dmg_value = True
    if self.cleaned_data['vit_interval_min'] or self.cleaned_data['vit_interval_max']:
        if (
            (self.cleaned_data['vit_interval_min'] if self.cleaned_data['vit_interval_min'] else 0)
            < crt_character.total_attack_interval
            < (self.cleaned_data['vit_interval_max'] if self.cleaned_data['vit_interval_max'] else 999999)
        ):
            good_vit_interval_value = True
    else:
        good_vit_interval_value = True
    if self.cleaned_data['rage_regen_min'] or self.cleaned_data['rage_regen_max']:
        if (
            (self.cleaned_data['rage_regen_min'] if self.cleaned_data['rage_regen_min'] else 0)
            < crt_character.total_rage_regen
            < (self.cleaned_data['rage_regen_max'] if self.cleaned_data['rage_regen_max'] else 999999)
        ):
            good_rage_regen_value = True
    else:
        good_rage_regen_value = True
    if self.cleaned_data['heal_effect_min'] or self.cleaned_data['heal_effect_max']:
        if (
            (self.cleaned_data['heal_effect_min'] if self.cleaned_data['heal_effect_min'] else 0)
            < crt_character.total_heal_effect
            < (self.cleaned_data['heal_effect_max'] if self.cleaned_data['heal_effect_max'] else 999999)
        ):
            good_heal_effect_value = True
    else:
        good_heal_effect_value = True
    if (
        good_hp_value
        and good_atk_value
        and good_def_value
        and good_crit_rate_value
        and good_crit_dmg_value
        and good_vit_interval_value
        and good_rage_regen_value
        and good_heal_effect_value
    ):
        return True
    else:
        return False


class CompareEquipmentForm(forms.Form):
    character: Character = forms.ModelChoiceField(queryset=Character.objects.all().order_by("name"))
    hp_min = forms.IntegerField(required=False, min_value=0)
    hp_max = forms.IntegerField(required=False, min_value=0)
    atk_min = forms.IntegerField(required=False, min_value=0)
    atk_max = forms.IntegerField(required=False, min_value=0)
    def_min = forms.IntegerField(required=False, min_value=0)
    def_max = forms.IntegerField(required=False, min_value=0)
    crit_rate_min = forms.IntegerField(required=False, min_value=0)
    crit_rate_max = forms.IntegerField(required=False, min_value=0)
    crit_dmg_min = forms.IntegerField(required=False, min_value=0)
    crit_dmg_max = forms.IntegerField(required=False, min_value=0)
    vit_interval_min = forms.FloatField(required=False, min_value=0)
    vit_interval_max = forms.FloatField(required=False, min_value=0)
    rage_regen_min = forms.IntegerField(required=False, min_value=0)
    rage_regen_max = forms.IntegerField(required=False, min_value=0)
    heal_effect_min = forms.IntegerField(required=False, min_value=0)
    heal_effect_max = forms.IntegerField(required=False, min_value=0)
    defense_reduction = forms.IntegerField(required=False, min_value=0, initial=0)
    use_equipped_items = forms.BooleanField(required=False)
    skill_buff = forms.ChoiceField(
        required=False,
        choices=(
            ("", "None"),
            ("Laurel", "Symbiotic Power (Laurel)"),
            ("Dolores", "Graceful Dancing (Dolores)"),
            ("Autumn", "Gold Maple's Room (Autumn)"),
        ),
    )
    dolo_skill_buff = forms.IntegerField(
        required=False,
        min_value=0,
        initial=0,
        widget=forms.TextInput(attrs={'placeholder': 'Dolores Total Attack', 'type': "number"}),
    )
    resultlist: list[list[object]] = []
    characterEquipList: list[Character] = []

    def compare(self) -> list[list[object]]:
        self.resultlist.clear()
        self.characterEquipList.clear()
        character: Character = self.cleaned_data["character"]
        weapon_equiped = Weapon.objects.all().filter(character_id__isnull=False)
        chestplate_equiped = Chestplate.objects.all().filter(character_id__isnull=False)
        wristband_equiped = Wristband.objects.all().filter(character_id__isnull=False)
        amulet_equiped = Amulet.objects.all().filter(character_id__isnull=False)
        ring_equiped = Ring.objects.all().filter(character_id__isnull=False)
        for weapon in Weapon.objects.all().exclude(
            id__in='' if self.cleaned_data['use_equipped_items'] else weapon_equiped
        ):
            for chestplate in Chestplate.objects.all().exclude(
                id__in='' if self.cleaned_data['use_equipped_items'] else chestplate_equiped
            ):
                for wristband in Wristband.objects.all().exclude(
                    id__in='' if self.cleaned_data['use_equipped_items'] else wristband_equiped
                ):
                    for amulet in Amulet.objects.all().exclude(
                        id__in='' if self.cleaned_data['use_equipped_items'] else amulet_equiped
                    ):
                        for ring in Ring.objects.all().exclude(
                            id__in='' if self.cleaned_data['use_equipped_items'] else ring_equiped
                        ):
                            crt_equipment: list[object] = []
                            crt_character: Character = copy.deepcopy(character)
                            crt_character.weapon = weapon
                            crt_character.chestplate = chestplate
                            crt_character.wristband = wristband
                            crt_character.amulet = amulet
                            crt_character.ring = ring
                            crt_character._defence_reduction = self.cleaned_data['defense_reduction']
                            crt_character._skill_buff = self.cleaned_data['skill_buff']
                            crt_character._dolo_skill_buff = self.cleaned_data['dolo_skill_buff']
                            crt_character._user_id = self.data['user_id'] if self.data['user_id'] != '' else 0
                            if equipment_goodvalue(self, crt_character):
                                crt_equipment.append(weapon)
                                crt_equipment.append(chestplate)
                                crt_equipment.append(wristband)
                                crt_equipment.append(amulet)
                                crt_equipment.append(ring)
                                self.characterEquipList.append(crt_character)
                                self.resultlist.append(crt_equipment)
        return self.resultlist


class CharacterForm(forms.ModelForm):
    class Meta:
        model = Character
        fields = [
            "rarity",
            "heroclass",
            "faction",
            "damagetype",
            "name",
            "health",
            "attack",
            "defense",
            "mRes",
            "cost",
            "block",
            "revival_time",
            "attack_interval",
            "crit_dmg",
            "attack_speed",
            "rage_regen",
            "rage_regen_auto",
            "rage_regen_basic_atk",
            "rage_regen_atked",
        ]


class WeaponForm(forms.ModelForm):
    class Meta:
        model = Weapon
        fields = [
            "main_stat_value",
            "first_stat",
            "first_stat_value",
            "second_stat",
            "second_stat_value",
            "third_stat",
            "third_stat_value",
            "fourth_stat",
            "fourth_stat_value",
            "set_name",
            "character",
        ]


class ChestplateForm(forms.ModelForm):
    class Meta:
        model = Chestplate
        fields = [

wor/templates/wor/form/amulet_form.html
{% extends 'wor/base.html' %}
{% load static %}

{% block title %}
   <title>Add Amulet</title>
{% endblock %}

{% block content %}
<link rel="stylesheet" href="{% static 'wor/add_form.css' %}">
<center><h1>Add Amulet</h1></center>
<div class="container">
   <form action="" method="post" novalidate>
       {% csrf_token %}
       {{ form }}
       <input type="submit" value="Save Amulet">
   </form>
</div>
{% endblock %}

wor/templates/wor/form/artifact_form.html
{% extends 'wor/base.html' %}
{% load static %}

{% block title %}
   <title>Add Artefact</title>
{% endblock %}

{% block content %}
<link rel="stylesheet" href="{% static 'wor/add_form.css' %}">
<center><h1>Add Artefact</h1></center>
<div class="container">
   <form action="" method="post" novalidate>
       {% csrf_token %}
       {{ form }}
       <input type="submit" value="Save Artefact">
   </form>
</div>
{% endblock %}

wor/templates/wor/form/character_form.html
{% extends 'wor/base.html' %}
{% load static %}

{% block title %}
   <title>Add Character</title>
{% endblock %}

{% block content %}
<link rel="stylesheet" href="{% static 'wor/add_form.css' %}">
<center><h1>Add Character</h1></center>
<div class="container">
   <form action="" method="post" novalidate>
       {% csrf_token %}
       {{ form }}
       <input type="submit" value="Save Character">
   </form>
</div>
{% endblock %}

wor/templates/wor/form/chestplate_form.html
{% extends 'wor/base.html' %}
{% load static %}

{% block title %}
   <title>Add Chestplate</title>
{% endblock %}

{% block content %}
<link rel="stylesheet" href="{% static 'wor/add_form.css' %}">
<center><h1>Add Chestplate</h1></center>
<div class="container">
   <form action="" method="post" novalidate>
       {% csrf_token %}
       {{ form }}
       <input type="submit" value="Save Chestplate">
   </form>
</div>
{% endblock %}

wor/templates/wor/form/collection_form.html
{% extends 'wor/base.html' %}
{% load static %}

{% block title %}
   <title>Add Collection Progress</title>
{% endblock %}

{% block content %}
<link rel="stylesheet" href="{% static 'wor/collection_form.css' %}">

<center><h1>Add Collection Progress</h1></center>
<div class="container">
	<div class="tab">
		{% for faction in factions %}
			{% if faction|stringformat:'s' != 'Unnamable' %}
				<button class="tablinks" onclick="openFaction(event, '{{faction}}')">{{faction}}</button>
			{% endif %}
		{% endfor %}
	</div>
	<form action="" method="post">
		{% csrf_token %}
		{% for faction in factions %}
			<div id="{{faction}}" class="tabcontent">
				<h3>{{faction}}</h3>
				{% if faction|stringformat:'s' == 'Watcher' %}
					<input type="text" value="{{faction}}" name="selected_faction" hidden="hidden"/>
					<div><div class="stats_grid-stat-title">HP +50</div>{{ form.hp50 }}</div>
					<div><div class="stats_grid-stat-title">HP +200</div>{{ form.hp200_watcher }}</div>
					<div><div>Rage Regen Atked</div>{{ form.rage_regen_atked }}</div>
				{% elif faction|stringformat:'s' == 'North' %}
					<input type="text" value="{{faction}}" name="selected_faction" hidden="hidden"/>
					<div><div class="stats_grid-stat-title">ATK +50</div>{{ form.atk50_north }}</div>
					<div><div class="stats_grid-stat-title">HP +200</div>{{ form.hp200_north }}</div>
					<div><div>Redeployment Time -5</div>{{ form.revival_time_minus_5 }}</div>
				{% elif faction|stringformat:'s' == 'Nightmare' %}
					<input type="text" value="{{faction}}" name="selected_faction" hidden="hidden"/>
					<div><div class="stats_grid-stat-title">ATK +50</div>{{ form.atk50_nightmare }}</div>
					<div><div class="stats_grid-stat-title">HP +200</div>{{ form.hp200_nightmare }}</div>
					<div><div>Rage Regen (Basic ATK) +1</div>{{ form.rage_regen_basic_atk_1_nightmare }}</div>
				{% elif faction|stringformat:'s' == 'Curse' %}
					<input type="text" value="{{faction}}" name="selected_faction" hidden="hidden"/>
					<div><div class="stats_grid-stat-title">ATK +50</div>{{ form.atk50_curse }}</div>
					<div><div class="stats_grid-stat-title">HP +200</div>{{ form.hp200_curse }}</div>
					<div><div>Crit. Rate +3%</div>{{ form.crit_rate_3 }}</div>
				{% elif faction|stringformat:'s' == 'Infernal' %}
					<input type="text" value="{{faction}}" name="selected_faction" hidden="hidden"/>
					<div><div class="stats_grid-stat-title">ATK +50</div>{{ form.atk50_infernal }}</div>
					<div><div class="stats_grid-stat-title">HP +200</div>{{ form.hp200_infernal }}</div>
					<div><div>Crit. DMG +5%</div>{{ form.crit_dmg_5 }}</div>
				{% elif faction|stringformat:'s' == 'Piercer' %}
					<input type="text" value="{{faction}}" name="selected_faction" hidden="hidden"/>
					<div><div class="stats_grid-stat-title">ATK +50</div>{{ form.atk50_piercer }}</div>
					<div><div class="stats_grid-stat-title">HP +200</div>{{ form.hp200_piercer }}</div>
					<div><div>Rage Regen (Basic ATK) +1</div>{{ form.rage_regen_basic_atk_1_piercer }}</div>
				{% elif faction|stringformat:'s' == 'Esoteric' %}
					<input type="text" value="{{faction}}" name="selected_faction" hidden="hidden"/>
					<div><div class="stats_grid-stat-title">ATK +50</div>{{ form.atk50_esoteric }}</div>
					<div><div class="stats_grid-stat-title">HP +200</div>{{ form.hp200_esoteric }}</div>
					<div><div>Initial Rage +30</div>{{ form.init_rage_30 }}</div>
				{% elif faction|stringformat:'s' == 'Chaos Dominion' %}
					<input type="text" value="{{faction}}" name="selected_faction" hidden="hidden"/>
					<div><div class="stats_grid-stat-title">ATK +50</div>{{ form.atk50_chaos_dominion }}</div>
					<div><div class="stats_grid-stat-title">HP +200</div>{{ form.hp200_chaos_dominion }}</div>
					<div><div class="stats_grid-stat-title">HP +400</div>{{ form.hp400 }}</div>
				{% elif faction|stringformat:'s' == 'Arbiters' %}
					<input type="text" value="{{faction}}" name="selected_faction" hidden="hidden"/>
					<div><div class="stats_grid-stat-title">ATK +50</div>{{ form.atk50_arbiters }}</div>
					<div><div class="stats_grid-stat-title">HP +200</div>{{ form.hp200_arbiters }}</div>
				{% endif %}
			</div>
		{% endfor %}
		<div class="submit">
			<input type="submit" value="Save Collection Progress">
		</div>
	</form>
	<script>
	function openFaction(evt, factionName) {
	  var i, tabcontent, tablinks;
	  tabcontent = document.getElementsByClassName("tabcontent");
	  for (i = 0; i < tabcontent.length; i++) {
		tabcontent[i].style.display = "none";
	  }
	  tablinks = document.getElementsByClassName("tablinks");
	  for (i = 0; i < tablinks.length; i++) {
		tablinks[i].className = tablinks[i].className.replace(" active", "");
	  }
	  document.getElementById(factionName).style.display = "block";
	  evt.currentTarget.className += " active";
	}
	</script>
</div>
{% endblock %}

wor/templates/wor/form/compare_equipment_form.html
{% extends 'wor/base.html' %}
{% load static %}

{% block title %}
<title>Compare Equipment</title>
{% endblock %}

{% block content %}
<link rel="stylesheet" href="{% static 'wor/compare.css' %}">
<center>
   <h1>Compare Equipment</h1>
</center>
<div class="container">
    <form method="post">
        {% csrf_token %}
        <div class="selectChar">
            <div>Select a Character for compare his equipment</div>
            {% if character_list %}
                {{ form.character }}
            {% else %}
                <p>No characters are available.</p>
            {% endif %}
        </div>
        <div class="stats_grid">
            <div></div>
            <div class="stats_grid-stat-header">Min</div>
            <div class="stats_grid-stat-header">Max</div>
            <div class="stats_grid-stat-title">HP</div>
            <div>{{ form.hp_min }}</div>
            <div>{{ form.hp_max }}</div>
            <div class="stats_grid-stat-title">Atk</div>
            <div>{{ form.atk_min }}</div>
            <div>{{ form.atk_max }}</div>
            <div class="stats_grid-stat-title">Def</div>
            <div>{{ form.def_min }}</div>
            <div>{{ form.def_max }}</div>
            <div class="stats_grid-stat-title">Crit. Rate</div>
            <div>{{ form.crit_rate_min }}</div>
            <div>{{ form.crit_rate_max }}</div>
            <div class="stats_grid-stat-title">Crit. Dmg</div>
            <div>{{ form.crit_dmg_min }}</div>
            <div>{{ form.crit_dmg_max }}</div>
            <div class="stats_grid-stat-title">Spd Interval</div>
            <div>{{ form.vit_interval_min }}</div>
            <div>{{ form.vit_interval_max }}</div>
            <div class="stats_grid-stat-title">Rage Regen</div>
            <div>{{ form.rage_regen_min }}</div>
            <div>{{ form.rage_regen_max }}</div>
            <div class="stats_grid-stat-title">Heal Effect</div>
            <div>{{ form.heal_effect_min }}</div>
            <div>{{ form.heal_effect_max }}</div>
            <div class="stats_grid-stat-title">Defense Reduction</div>
            <div>{{ form.defense_reduction }}</div>
        </div>
        <div>Use equipped items {{ form.use_equipped_items }}</div>
        <div>Skill Buff
            <select name="skill_buff" id="id_skill_buff" onChange="openSkillBuffInput()">
                {% for skill_buff in form.skill_buff %}
                    {{ skill_buff }}
            {% endfor %}
            </select>
            <div id="dolo_skill_buff">{{ form.dolo_skill_buff }}</div>
            <input type="text" value="{{ user_id }}" name="user_id" hidden="hidden"/>
        </div>
        <input type="submit" value="Launch Compare">
    </form>
    <script>
        doloSkillBbuff = document.getElementById("dolo_skill_buff");
        doloSkillBbuff.style.display = "none";
        function openSkillBuffInput() {
            var id_skill_buff = document.getElementById("id_skill_buff").value;
            doloSkillBbuff = document.getElementById("dolo_skill_buff");
            if(id_skill_buff == "Dolores") {
                doloSkillBbuff.style.display = "block";
            } else {
                doloSkillBbuff.style.display = "none";
            }
        }
    </script>
    {% if result_list %}
    <table>
        <thead>
            <tr>
                <th scope="col">HP</th>
                <th scope="col">ATK</th>
                <th scope="col">DEF</th>
                <th scope="col">Crit. Rate</th>
                <th scope="col">Crit. DMG</th>
                <th scope="col">Spd Interval</th>
                <th scope="col">Rage Regen</th>
                <th scope="col">Heal Effect</th>
                <th scope="col">DPS Estimate</th>
                <th scope="col">View Equipment</th>
            </tr>
        </thead>
        {% for characterEquip in characterEquipList %}
            {% for result in result_list %}
                {% if forloop.counter == forloop.parentloop.counter %}
                    <tr>
                        <td>{{ characterEquip.total_hp }}</td>
                        <td>{{ characterEquip.total_atk }}</td>
                        <td>{{ characterEquip.total_def }}</td>
                        <td>{{ characterEquip.total_crit_rate }}</td>
                        <td>{{ characterEquip.total_crit_dmg }}</td>
                        <td>{{ characterEquip.total_attack_interval }}</td>
                        <td>{{ characterEquip.total_rage_regen }}</td>
                        <td>{{ characterEquip.total_heal_effect }}</td>
                        <td>{{ characterEquip.total_dps }}</td>
                        <td>
                            <button>
                                <a href="{% url 'wor:compare_equipment_url'%}?result_id={{ forloop.counter }}">View</a>
                            </button>
                        </td>
                    </tr>
                {% endif %}
            {% endfor %}
        {% endfor %}
    </table>
    {% else %}
        <p>Your character already has the best equipment available !</p>
    {% endif %}
    {% if result %}
        {% for equipment in result %}
            {% if equipment.get_model_type == 'Weapon' %}
                <h2>Weapon</h2>
            {% elif equipment.get_model_type == 'Chestplate' %}
                <h2>Chestplate</h2>
            {% elif equipment.get_model_type == 'Wristband' %}
                <h2>Wristband</h2>
            {% elif equipment.get_model_type == 'Amulet' %}
                <h2>Amulet</h2>
            {% elif equipment.get_model_type == 'Ring' %}
                <h2>Ring</h2>
            {% endif %}
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">Main stat</th>
                        <th scope="col">Main Stat Value</th>
                        <th scope="col">First Stat</th>
                        <th scope="col">First Stat Value</th>
                        <th scope="col">Second Stat</th>
                        <th scope="col">Second Stat Value</th>
                        <th scope="col">Third Stat</th>
                        <th scope="col">Third Stat Value</th>
                        <th scope="col">Fourth Stat</th>
                        <th scope="col">Fourth Stat Value</th>
                        <th scope="col">Set Name</th>
                        <th scope="col">Set Bonus</th>
                        <th scope="col">Character</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>{{ equipment.main_stat }}</td>
                        <td>{{ equipment.main_stat_value }}</td>
                        <td>{{ equipment.first_stat }}</td>
                        <td>{{ equipment.first_stat_value }}</td>
                        <td>{{ equipment.second_stat }}</td>
                        <td>{{ equipment.second_stat_value }}</td>
                        <td>{{ equipment.third_stat }}</td>
                        <td>{{ equipment.third_stat_value }}</td>
                        <td>{{ equipment.fourth_stat }}</td>
                        <td>{{ equipment.fourth_stat_value }}</td>
                        <td>{{ equipment.set_name }}</td>
                        <td>{{ equipment.set_bonus }}</td>
                        <td>{{ equipment.character }}</td>
                    </tr>
                </tbody>
            </table>
        {% endfor %}
    {% endif %}
</div>
{% endblock %}

wor/templates/wor/form/pantheon_form.html
{% extends 'wor/base.html' %}
{% load static %}

{% block title %}
   <title>Add Pantheon</title>
{% endblock %}

{% block content %}
<link rel="stylesheet" href="{% static 'wor/add_form.css' %}">
<center><h1>Add Pantheon</h1></center>
<div class="container">
   <form action="" method="post" novalidate>
       {% csrf_token %}
       {{ form }}
       <input type="submit" value="Save Pantheon">
   </form>
</div>
{% endblock %}