src/urls.py
from debug_toolbar.toolbar import debug_toolbar_urls
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("wor.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
] + debug_toolbar_urls()

wor/urls.py
from django.urls import path

from . import views

app_name = "wor"
urlpatterns = [
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path("", views.index_show_view, name="index"),
    path("compareEquipmentForm/", views.compare_equipment_form_view, name="compare_equipment_url"),
    path("characterShow/", views.CharacterView.as_view(), name="show_character_url"),
    path("characterForm/", views.character_form_view, name="character_url"),
    path("weaponForm/", views.weapon_form_view, name="weapon_url"),
    path("chestplateForm/", views.chestplate_form_view, name="chestplate_url"),
    path("wristbandForm/", views.wristband_form_view, name="wristband_url"),
    path("amuletForm/", views.amulet_form_view, name="amulet_url"),
    path("ringForm/", views.ring_form_view, name="ring_url"),
    path("pantheonForm/", views.pantheon_form_view, name="pantheon_url"),
    path("artifactForm/", views.artifact_form_view, name="artifact_url"),
    path("collectionForm/", views.collection_form_view, name="collection_url"),
    path("weaponShow/", views.weapon_show_view, name="show_weapon_url"),
    path("chestplateShow/", views.chestplate_show_view, name="show_chestplate_url"),
    path("wristbandShow/", views.wristband_show_view, name="show_wristband_url"),
    path("amuletShow/", views.amulet_show_view, name="show_amulet_url"),
    path("ringShow/", views.ring_show_view, name="show_ring_url"),
    path("pantheon/", views.pantheon_show_view, name="show_pantheon_url"),
    path("artifact/", views.artifact_show_view, name="show_artifact_url"),
    path("collection/", views.collection_show_view, name="show_collection_url"),
    path("character/<int:f_id>/change", views.character_update_view, name="update_character_url"),
    path("weapon/<int:f_id>/change", views.weapon_update_view, name="update_weapon_url"),
    path("chestplate/<int:f_id>/change", views.chestplate_update_view, name="update_chestplate_url"),
    path("wristband/<int:f_id>/change", views.wristband_update_view, name="update_wristband_url"),
    path("amulet/<int:f_id>/change", views.amulet_update_view, name="update_amulet_url"),
    path("ring/<int:f_id>/change", views.ring_update_view, name="update_ring_url"),
    path("pantheon/<int:f_id>/change", views.pantheon_update_view, name="update_pantheon_url"),
    path("artifact/<int:f_id>/change", views.artifact_update_view, name="update_artifact_url"),
    path("collection/<int:f_id>/change", views.collection_update_view, name="update_collection_url"),
    path("weapon/<int:f_id>/delete", views.weapon_delete_view, name="delete_weapon_url"),
    path("chestplate/<int:f_id>/delete", views.chestplate_delete_view, name="delete_chestplate_url"),
    path("wristband/<int:f_id>/delete", views.wristband_delete_view, name="delete_wristband_url"),
    path("amulet/<int:f_id>/delete", views.amulet_delete_view, name="delete_amulet_url"),
    path("ring/<int:f_id>/delete", views.ring_delete_view, name="delete_ring_url"),
    path("artifact/<int:f_id>/change", views.artifact_delete_view, name="delete_artifact_url"),
    path("weapon/<int:id>", views.weapon_detail, name="weapon-detail"),
    path("chestplate/<int:id>/", views.chestplate_detail, name="chestplate-detail"),
    path("wristband/<int:id>/", views.wristband_detail, name="wristband-detail"),
    path("amulet/<int:id>/", views.amulet_detail, name="amulet-detail"),
    path("ring/<int:id>/", views.ring_detail, name="ring-detail"),
    path("character/<int:id>/", views.character_detail, name="character-detail"),
]

wor/views.py
from django.contrib.auth import get_user
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.views import generic
from django.views.generic import CreateView

from .forms import (
    AmuletForm,
    CharacterForm,
    ChestplateForm,
    CompareEquipmentForm,
    RingForm,
    WeaponForm,
    WristbandForm,
    PantheonForm,
    ArtifactForm,
    CollectionForm,
    WatcherCollectionForm,
    NorthCollectionForm,
    CurseCollectionForm,
    InfernalCollectionForm,
    NightmareCollectionForm,
    ChaosDominionCollectionForm,
    PiercerCollectionForm,
    EsotericCollectionForm,
    ArbitersCollectionForm,
)
from .models import Amulet, Character, Chestplate, Ring, Weapon, Wristband, Pantheon, Artifact, Collection, Faction

resultlist: list[object] = []


class SignUpView(CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy("login")
    template_name = "wor/registration/signup.html"


@login_required
def index_show_view(request):
    template_name = "wor/base.html"
    return render(request, template_name)


def compare_equipment_form_view(request):
    template_name = "wor/form/compare_equipment_form.html"
    user: User = get_user(request)
    if request.method == "POST":
        form = CompareEquipmentForm(request.POST)
        if form.is_valid():
            context = {
                "form": form,
                "character_list": Character.objects.order_by("name"),
                "result_list": form.compare(),
                "characterEquipList": form.characterEquipList,
                "user_id": user.id,
            }
            return render(request, template_name, context)
    if request.method == "GET" and len(CompareEquipmentForm(request.GET).resultlist) > 0:
        form = CompareEquipmentForm(request.GET)
        context = {
            "result": form.resultlist[int(request.GET.get("result_id"))] if request.GET.get("result_id") else None,
            "form": form,
            "character_list": Character.objects.order_by("name"),
            "result_list": form.resultlist,
            "characterEquipList": form.characterEquipList,
            "user_id": user.id,
        }
        CompareEquipmentForm(request.GET).resultlist = []
        return render(request, template_name, context)
    form = CompareEquipmentForm()
    context = {
        "form": form,
        "character_list": Character.objects.order_by("name"),
        "user_id": user.id,
    }
    return render(request, template_name, context)


class CharacterView(generic.ListView):
    template_name = "wor/show/characters.html"
    context_object_name = "character_list"

    def get_queryset(self):
        return Character.objects.order_by("name")


def character_detail(request, id):
    character = Character.objects.get(id=id)
    user: User = get_user(request)
    character.user_id = user.id
    template_name = "wor/detail/character_detail.html"
    context = {"character": character}
    return render(request, template_name, context)


def character_form_view(request):
    form = CharacterForm()
    if request.method == "POST":
        form = CharacterForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("wor:show_character_url")
    template_name = "wor/form/character_form.html"
    context = {"form": form}
    return render(request, template_name, context)


def weapon_form_view(request):
    form = WeaponForm()
    if request.method == "POST":
        form = WeaponForm(request.POST)
        user: User = get_user(request)
        form.user = user
        form.instance.user_id = user.id
        if form.is_valid():
            form.save()
            return redirect("wor:show_weapon_url")
    template_name = "wor/form/weapon_form.html"
    context = {"form": form}
    return render(request, template_name, context)


def chestplate_form_view(request):
    form = ChestplateForm()
    if request.method == "POST":
        form = ChestplateForm(request.POST)
        user: User = get_user(request)
        form.user = user
        form.instance.user_id = user.id
        if form.is_valid():
            form.save()
            return redirect("wor:show_chestplate_url")
    template_name = "wor/form/chestplate_form.html"
    context = {"form": form}
    return render(request, template_name, context)


def wristband_form_view(request):
    form = WristbandForm()
    if request.method == "POST":
        form = WristbandForm(request.POST)
        user: User = get_user(request)
        form.user = user
        form.instance.user_id = user.id
        if form.is_valid():
            form.save()
            return redirect("wor:show_wristband_url")
    template_name = "wor/form/wristband_form.html"
    context = {"form": form}
    return render(request, template_name, context)


def amulet_form_view(request):
    form = AmuletForm()
    if request.method == "POST":
        form = AmuletForm(request.POST)
        user: User = get_user(request)
        form.user = user
        form.instance.user_id = user.id
        if form.is_valid():
            form.save()
            return redirect("wor:show_amulet_url")
    template_name = "wor/form/amulet_form.html"
    context = {"form": form}
    return render(request, template_name, context)


def ring_form_view(request):
    form = RingForm()
    if request.method == "POST":
        form = RingForm(request.POST)
        user: User = get_user(request)
        form.user = user
        form.instance.user_id = user.id
        if form.is_valid():
            form.save()
            return redirect("wor:show_ring_url")
    template_name = "wor/form/ring_form.html"
    context = {"form": form}
    return render(request, template_name, context)


def pantheon_form_view(request):
    form = PantheonForm()
    if request.method == "POST":
        form = PantheonForm(request.POST)
        user: User = get_user(request)
        form.user = user
        form.instance.user_id = user.id
        if form.is_valid():
            form.save()
            return redirect("wor:show_pantheon_url")
    template_name = "wor/form/pantheon_form.html"
    context = {"form": form}
    return render(request, template_name, context)


def artifact_form_view(request):
    form = ArtifactForm()
    if request.method == "POST":
        form = ArtifactForm(request.POST)
        user: User = get_user(request)
        form.user = user
        form.instance.user_id = user.id
        if form.is_valid():
            form.save()
            return redirect("wor:show_artifact_url")
    template_name = "wor/form/artifact_form.html"
    context = {"form": form}
    return render(request, template_name, context)


def collection_form_view(request):
    form = CollectionForm()
    user: User = get_user(request)
    if request.method == "POST":
        updated_request = request.POST.copy()
        faction: Faction = Faction.objects.get(faction=Faction.FactionEnum.WATCHER)
        updated_request.update({'faction': faction})
        form = WatcherCollectionForm(updated_request)
        form.user = user
        form.instance.user_id = user.id
        if form.is_valid():
            form.save()
        faction: Faction = Faction.objects.get(faction=Faction.FactionEnum.NORTH)
        updated_request.update({'faction': faction})
        form = NorthCollectionForm(updated_request)
        form.user = user
        form.instance.user_id = user.id
        if form.is_valid():
            form.save()
        faction: Faction = Faction.objects.get(faction=Faction.FactionEnum.CURSE)
        updated_request.update({'faction': faction})
        form = CurseCollectionForm(updated_request)
        form.user = user
        form.instance.user_id = user.id
        if form.is_valid():
            form.save()
        faction: Faction = Faction.objects.get(faction=Faction.FactionEnum.NIGHTMARE)
        updated_request.update({'faction': faction})
        form = NightmareCollectionForm(updated_request)
        form.user = user
        form.instance.user_id = user.id
        if form.is_valid():
            form.save()
        faction: Faction = Faction.objects.get(faction=Faction.FactionEnum.INFERNAL)
        updated_request.update({'faction': faction})
        form = InfernalCollectionForm(updated_request)
        form.user = user
        form.instance.user_id = user.id
        if form.is_valid():
            form.save()
        faction: Faction = Faction.objects.get(faction=Faction.FactionEnum.PIERCER)
        updated_request.update({'faction': faction})
        form = PiercerCollectionForm(updated_request)
        form.user = user
        form.instance.user_id = user.id
        if form.is_valid():
            form.save()
        faction: Faction = Faction.objects.get(faction=Faction.FactionEnum.ESOTERIC)
        updated_request.update({'faction': faction})
        form = EsotericCollectionForm(updated_request)
        form.user = user
        form.instance.user_id = user.id
        if form.is_valid():
            form.save()
        faction: Faction = Faction.objects.get(faction=Faction.FactionEnum.CHAOS_DOMINION)
        updated_request.update({'faction': faction})
        form = ChaosDominionCollectionForm(updated_request)
        form.user = user
        form.instance.user_id = user.id
        if form.is_valid():
            form.save()
        faction: Faction = Faction.objects.get(faction=Faction.FactionEnum.ARBITERS)
        updated_request.update({'faction': faction})
        form = ArbitersCollectionForm(updated_request)
        form.user = user
        form.instance.user_id = user.id
        if form.is_valid():
            form.save()
        return redirect("wor:show_collection_url")
    template_name = "wor/form/collection_form.html"
    factions = Faction.objects.all()

wor/templates/wor/show/amulets.html
{% extends 'wor/base.html' %}
{% load static %}

{% block title %}
   <title>Show Amulets</title>
{% endblock %}

{% block content %}
<link rel="stylesheet" href="{% static 'wor/show_equipment.css' %}">
<center><h1>Show Amulets</h1></center>
<table class="table">
    <thead>
        <tr>
            <th scope="col">Main stat</th>
            <th scope="col">Main Stat Value</th>
            <th scope="col">First Stat</th>
            <th scope="col">First Stat Value</th>
            <th scope="col">Second Stat</th>
            <th scope="col">Second Stat Value</th>
            <th scope="col">Third Stat</th>
            <th scope="col">Third Stat Value</th>
            <th scope="col">Fourth Stat</th>
            <th scope="col">Fourth Stat Value</th>
            <th scope="col">Set Name</th>
            <th scope="col">Set Bonus</th>
            <th scope="col">Character</th>
        </tr>
    </thead>
    <tbody>
        {% for amulet in amulets %}
            <tr>
                <td>{{amulet.main_stat}}</td>
                <td>{{amulet.main_stat_value}}</td>
                <td>{{amulet.first_stat}}</td>
                <td>{{amulet.first_stat_value}}</td>
                <td>{{amulet.second_stat}}</td>
                <td>{{amulet.second_stat_value}}</td>
                <td>{{amulet.third_stat}}</td>
                <td>{{amulet.third_stat_value}}</td>
                <td>{{amulet.fourth_stat}}</td>
                <td>{{amulet.fourth_stat_value}}</td>
                <td>{{amulet.set_name}}</td>
                <td>{{amulet.set_bonus}}</td>
                 <td>{{amulet.character}}</td>
                <td>
                   <button class="btn btn-warning">
                       <a href="{% url 'wor:update_amulet_url' amulet.id %}">Update</a>
                   </button>
                   <button class="btn btn-danger">
                       <a href="{% url 'wor:delete_amulet_url' amulet.id %}">Delete</a>
                   </button>
                </td>
            </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

wor/templates/wor/show/artifacts.html
{% extends 'wor/base.html' %}
{% load static %}

{% block title %}
   <title>Show Artifacts</title>
{% endblock %}

{% block content %}
<link rel="stylesheet" href="{% static 'wor/show_equipment.css' %}">
<center><h1>Show Artifacts</h1></center>
<table class="table">
    <thead>
        <tr>
            <th scope="col">HP</th>
            <th scope="col">ATK</th>
            <th scope="col">Character</th>
        </tr>
    </thead>
   <tbody>
   {% for artifact in artifacts %}
     <tr>
        <td>{{ artifact.hp }}</td>
        <td>{{ artifact.atk }}</td>
        <td>{{ artifact.character }}</td>
       <td>
           <button class="btn btn-warning">
               <a href="{% url 'wor:update_artifact_url' artifact.id %}">Update</a>
           </button>
           <button class="btn btn-danger">
               <a href="{% url 'wor:delete_artifact_url' artifact.id %}">Delete</a>
           </button>
       </td>
     </tr>
   {% endfor %}
   </tbody>
 </table>
{% endblock %}

wor/templates/wor/show/characters.html
{% extends 'wor/base.html' %}
{% load static %}

{% block title %}
   <title>Show Characters</title>
{% endblock %}

{% block content %}
<link rel="stylesheet" href="{% static 'wor/style.css' %}">
{% if character_list %}
    {% for character in character_list %}
        <a href="{% url 'wor:character-detail' character.id %}">
            <img width="90" src="{% get_static_prefix %}wor/images/icons/heroes/{{ character.name }}.png">
        </a>
        <a href="{% url 'wor:update_character_url' character.id %}">Update</a>
    {% endfor %}
{% else %}
    <p>No wor are available.</p>
{% endif %}

{% endblock %}

wor/templates/wor/show/chestplates.html
{% extends 'wor/base.html' %}
{% load static %}

{% block title %}
   <title>Show Chestplates</title>
{% endblock %}

{% block content %}
<link rel="stylesheet" href="{% static 'wor/show_equipment.css' %}">
<center><h1>Show Chestplates</h1></center>
<table class="table">
    <thead>
        <tr>
            <th scope="col">Main stat</th>
            <th scope="col">Main Stat Value</th>
            <th scope="col">First Stat</th>
            <th scope="col">First Stat Value</th>
            <th scope="col">Second Stat</th>
            <th scope="col">Second Stat Value</th>
            <th scope="col">Third Stat</th>
            <th scope="col">Third Stat Value</th>
            <th scope="col">Fourth Stat</th>
            <th scope="col">Fourth Stat Value</th>
            <th scope="col">Set Name</th>
            <th scope="col">Set Bonus</th>
            <th scope="col">Character</th>
        </tr>
    </thead>
    <tbody>
        {% for chestplate in chestplates %}
            <tr>
                <td>{{chestplate.main_stat}}</td>
                <td>{{chestplate.main_stat_value}}</td>
                <td>{{chestplate.first_stat}}</td>
                <td>{{chestplate.first_stat_value}}</td>
                <td>{{chestplate.second_stat}}</td>
                <td>{{chestplate.second_stat_value}}</td>
                <td>{{chestplate.third_stat}}</td>
                <td>{{chestplate.third_stat_value}}</td>
                <td>{{chestplate.fourth_stat}}</td>
                <td>{{chestplate.fourth_stat_value}}</td>
                <td>{{chestplate.set_name}}</td>
                <td>{{chestplate.set_bonus}}</td>
                <td>{{chestplate.character}}</td>
                <td>
                <button class="btn btn-warning">
                    <a href="{% url 'wor:update_chestplate_url' chestplate.id %}">Update</a>
                </button>
                <button class="btn btn-danger">
                    <a href="{% url 'wor:delete_chestplate_url' chestplate.id %}">Delete</a>
                </button>
                </td>
            </tr>
        {% endfor %}
    </tbody>
    </table>
{% endblock %}

wor/templates/wor/show/collections.html
{% extends 'wor/base.html' %}
{% load static %}

{% block title %}
   <title>Show Collection Progress</title>
{% endblock %}

{% block content %}
    <link rel="stylesheet" href="{% static 'wor/show_equipment.css' %}">
    <center><h1>Show Collection Progress</h1></center>
    {% if collections %}
    <table class="table">
        <thead>
            <tr>
                <th scope="col">Faction</th>
                <th scope="col">HP +50</th>
                <th scope="col">HP +200</th>
                <th scope="col">HP +400</th>
                <th scope="col">Rage Regen (Attacked) +1</th>
                <th scope="col">Atk +50</th>
                <th scope="col">Redeployment Time -5</th>
                <th scope="col">Rage Regen (Basic ATK) +1</th>
                <th scope="col">Crit Rate +3%</th>
                <th scope="col">Crit Dmg +5%</th>
                <th scope="col">Init Rage +30</th>
            </tr>
        </thead>
        <tbody>
            {% for collection in collections %}
                <tr>
                    <td>{{ collection.faction }}</td>
                    {% if collection.faction|stringformat:'s' == 'Watcher' %}
                        <td>{{ collection.hp50 }}</td>
                    {% else %}
                        <td></td>
                    {% endif %}
                    {% if collection.faction|stringformat:'s' == 'Watcher' %}
                        <td>{{ collection.hp200_watcher }}</td>
                    {% elif collection.faction|stringformat:'s' == 'North' %}
                        <td>{{ collection.hp200_north }}</td>
                    {% elif collection.faction|stringformat:'s' == 'Nightmare' %}
                        <td>{{ collection.hp200_nightmare }}</td>
                    {% elif collection.faction|stringformat:'s' == 'Curse' %}
                        <td>{{ collection.hp200_curse }}</td>
                    {% elif collection.faction|stringformat:'s' == 'Infernal' %}
                        <td>{{ collection.hp200_infernal }}</td>
                    {% elif collection.faction|stringformat:'s' == 'Piercer' %}
                        <td>{{ collection.hp200_piercer }}</td>
                    {% elif collection.faction|stringformat:'s' == 'Esoteric' %}
                        <td>{{ collection.hp200_esoteric }}</td>
                    {% elif collection.faction|stringformat:'s' == 'Chaos Dominion' %}
                        <td>{{ collection.hp200_chaos_dominion }}</td>
                    {% elif collection.faction|stringformat:'s' == 'Arbiters' %}
                        <td>{{ collection.hp200_arbiters }}</td>
                    {% endif %}
                    {% if collection.faction|stringformat:'s' == 'Chaos Dominion' %}
                        <td>{{ collection.hp400 }}</td>
                    {% else %}
                        <td></td>
                    {% endif %}
                    {% if collection.faction|stringformat:'s' == 'Watcher' %}
                        <td>{{ collection.rage_regen_atked }}</td>
                    {% else %}
                        <td></td>
                    {% endif %}
                    {% if collection.faction|stringformat:'s' == 'North' %}
	                    <td>{{ collection.atk50_north }}</td>
                    {% elif collection.faction|stringformat:'s' == 'Nightmare' %}
                        <td>{{ collection.atk50_nightmare }}</td>
                    {% elif collection.faction|stringformat:'s' == 'Curse' %}
                        <td>{{ collection.atk50_curse }}</td>
                    {% elif collection.faction|stringformat:'s' == 'Infernal' %}
                        <td>{{ collection.atk50_infernal }}</td>
                    {% elif collection.faction|stringformat:'s' == 'Piercer' %}
                        <td>{{ collection.atk50_piercer }}</td>
                    {% elif collection.faction|stringformat:'s' == 'Esoteric' %}
                        <td>{{ collection.atk50_esoteric }}</td>
                    {% elif collection.faction|stringformat:'s' == 'Chaos Dominion' %}
                        <td>{{ collection.atk50_chaos_dominion }}</td>
                    {% elif collection.faction|stringformat:'s' == 'Arbiters' %}
                        <td>{{ collection.atk50_arbiters }}</td>
                    {% else %}
                        <td></td>
                    {% endif %}
                    {% if collection.faction|stringformat:'s' == 'North' %}
                        <td>{{ collection.revival_time_minus_5 }}</td>
                    {% else %}
                        <td></td>
                    {% endif %}
                    {% if collection.faction|stringformat:'s' == 'Nightmare' %}
                        <td>{{ collection.rage_regen_basic_atk_1_nightmare }}</td>
                    {% elif collection.faction|stringformat:'s' == 'Piercer' %}
                        <td>{{ collection.rage_regen_basic_atk_1_piercer }}</td>
                    {% else %}
                        <td></td>
                    {% endif %}
                    {% if collection.faction|stringformat:'s' == 'Curse' %}
                        <td>{{ collection.crit_rate_3 }}</td>
                    {% else %}
                        <td></td>
                    {% endif %}
                    {% if collection.faction|stringformat:'s' == 'Infernal' %}
                        <td>{{ collection.crit_dmg_5 }}</td>
                    {% else %}
                        <td></td>
                    {% endif %}
                    {% if collection.faction|stringformat:'s' == 'Esoteric' %}
                        <td>{{ collection.init_rage_30 }}</td>
                    {% else %}
                        <td></td>
                    {% endif %}
                    <td>
                        <button class="btn btn-warning">
                            <a href="{% url 'wor:update_collection_url' collection.id %}">Update</a>
                        </button>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    {% else %}
        <div>No Collections available for your account ! You can create it for this link
            <button>
                <a href="{% url 'wor:collection_url'%}">Add Collection</a>
            </button>
        </div>
    {% endif %}
{% endblock %}

wor/templates/wor/show/pantheon.html
{% extends 'wor/base.html' %}
{% load static %}

{% block title %}
   <title>Show Pantheon</title>
{% endblock %}

{% block content %}
    <link rel="stylesheet" href="{% static 'wor/show_equipment.css' %}">
    <center><h1>Show Pantheon</h1></center>
    {% if pantheon %}
    <table class="table">
        <thead>
            <tr>
                <th scope="col">Atk Bonus</th>
                <th scope="col">HP Bonus</th>
                <th scope="col">Rage Regen</th>
                <th scope="col">Crit. DMG</th>
                <th scope="col">Healing Effect</th>
                <th scope="col">Atk Spd.</th>
                <th scope="col">Def Bonus</th>
                <th scope="col">mRes Bonus</th>
                <th scope="col">Crit. Rate</th>
                <th scope="col">Rage Regen Auto</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>{{ pantheon.atk_bonus }}</td>
                <td>{{ pantheon.hp_bonus }}</td>
                <td>{{ pantheon.rage_regen }}</td>
                <td>{{ pantheon.crit_dmg }}</td>
                <td>{{ pantheon.healing_effect }}</td>
                <td>{{ pantheon.atk_spd }}</td>
                <td>{{ pantheon.def_bonus }}</td>
                <td>{{ pantheon.mRes_bonus }}</td>
                <td>{{ pantheon.crit_rate }}</td>
                <td>{{ pantheon.ragen_regen_auto }}</td>
                <td>
                    <button class="btn btn-warning">
                        <a href="{% url 'wor:update_pantheon_url' pantheon.id %}">Update</a>
                    </button>
                </td>
            </tr>
        </tbody>
    </table>
    {% else %}
        <div>No Pantheon available for your account ! You can create it for this link
            <button>
                <a href="{% url 'wor:pantheon_url'%}">Add Pantheon </a>
            </button>
        </div>
    {% endif %}
{% endblock %}

wor/templates/wor/show/weapons.html
{% extends 'wor/base.html' %}
{% load static %}

{% block title %}
   <title>Show Weapons</title>
{% endblock %}

{% block content %}
<link rel="stylesheet" href="{% static 'wor/show_equipment.css' %}">
<center><h1>Show Weapons</h1></center>
<table class="table">
    <thead>
        <tr>
            <th scope="col">Main stat</th>
            <th scope="col">Main Stat Value</th>
            <th scope="col">First Stat</th>
            <th scope="col">First Stat Value</th>
            <th scope="col">Second Stat</th>
            <th scope="col">Second Stat Value</th>
            <th scope="col">Third Stat</th>
            <th scope="col">Third Stat Value</th>
            <th scope="col">Fourth Stat</th>
            <th scope="col">Fourth Stat Value</th>
            <th scope="col">Set Name</th>
            <th scope="col">Set Bonus</th>
            <th scope="col">Character</th>
        </tr>
    </thead>
    <tbody>
        {% for weapon in weapons %}
            <tr>
                <td><a href="{% url 'wor:weapon-detail' weapon.id %}">{{weapon.main_stat}}</a></td>
                <td>{{ weapon.main_stat_value }}</td>
                <td>{{ weapon.first_stat }}</td>
                <td>{{ weapon.first_stat_value }}</td>
                <td>{{ weapon.second_stat }}</td>
                <td>{{ weapon.second_stat_value }}</td>
                <td>{{ weapon.third_stat }}</td>
                <td>{{ weapon.third_stat_value }}</td>
                <td>{{ weapon.fourth_stat }}</td>
                <td>{{ weapon.fourth_stat_value }}</td>
                <td>{{ weapon.set_name }}</td>
                <td>{{ weapon.set_bonus }}</td>
                <td>{{ weapon.character }}</td>
                <td>
                    <button class="btn btn-warning">
                        <a href="{% url 'wor:update_weapon_url' weapon.id %}">Update</a>
                    </button>
                    <button class="btn btn-danger">
                        <a href="{% url 'wor:delete_weapon_url' weapon.id %}">Delete</a>
                    </button>
                </td>
            </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}